feat: add translate at the homepage WIP
feature-sh/website pull request #66
Opened 2023-03-14 17:01 UTC by BLOCKCHAINDEVWEB

I need to change the dimension of the texts or to adapt the text to the cell and this with the French and English language.

2023-03-17 10:43 UTC, n1c01a5 requested changes

2023-03-17 10:43 UTC, n1c01a5 commented on pages/index.tsx
> +          {translate('title_h1')}
Use something more explicit like `title_main`.

2023-03-17 10:43 UTC, n1c01a5 commented on pages/index.tsx
> +            {translate('title_h2')}
Use something more explicit like `subtitle_main`.

2023-03-17 10:43 UTC, n1c01a5 commented on public/locales/fr/homepage.json
> +  "title_h1": "OUTIL DE TRAVAIL WEB3",
Keep `DEVTOOL WEB3`.

2023-03-17 10:43 UTC, n1c01a5 commented on public/locales/fr/homepage.json
> +  "build_trustless_title_section": "CONSTRUIRE SANS CONFIANCE",
"build_trustless_title_section": "+ CONFIANCE"

2023-03-17 10:43 UTC, n1c01a5 commented on public/locales/fr/homepage.json
> +  "build_faster_title_section": "CONSTRUIRE PLUS VITE",
"build_faster_title_section": "+ RAPIDE",

2023-03-17 10:43 UTC, n1c01a5 commented on public/locales/fr/homepage.json
> +  "build_faster_text3_row1_section": "Payer les cotisants",
"build_faster_text3_row1_section": "Payer les contributeurs",

2023-03-17 10:43 UTC, n1c01a5 commented on public/locales/fr/homepage.json
> +  "features_more": "Plus de fonctionnalités",
"features_more": "Fonctionnalités",

2023-03-17 10:43 UTC, n1c01a5 commented on public/locales/fr/homepage.json
> +  "build_cheaper_title_section": "CONSTRUIRE MOINS CHER",
"build_cheaper_title_section": "- CHER",

2023-03-17 11:27 UTC, BLOCKCHAINDEVWEB commented on pages/index.tsx
> +          {translate('title_h1')}
ok

2023-03-17 11:27 UTC, BLOCKCHAINDEVWEB commented on pages/index.tsx
> +            {translate('title_h2')}
ok

2023-03-17 11:27 UTC, BLOCKCHAINDEVWEB commented on public/locales/fr/homepage.json
> +  "title_h1": "OUTIL DE TRAVAIL WEB3",
ok

2023-03-17 11:28 UTC, BLOCKCHAINDEVWEB commented on public/locales/fr/homepage.json
> +  "build_faster_title_section": "CONSTRUIRE PLUS VITE",
ok

2023-03-17 11:28 UTC, BLOCKCHAINDEVWEB commented on public/locales/fr/homepage.json
> +  "build_faster_text3_row1_section": "Payer les cotisants",
ok

2023-03-17 11:28 UTC, BLOCKCHAINDEVWEB commented on public/locales/fr/homepage.json
> +  "build_cheaper_title_section": "CONSTRUIRE MOINS CHER",
ok

2023-03-17 11:28 UTC, BLOCKCHAINDEVWEB commented on public/locales/fr/homepage.json
> +  "build_trustless_title_section": "CONSTRUIRE SANS CONFIANCE",
ok

2023-03-17 11:28 UTC, BLOCKCHAINDEVWEB commented on public/locales/fr/homepage.json
> +  "features_more": "Plus de fonctionnalités",
ok

2023-04-17 08:45 UTC, n1c01a5 commented on public/locales/fr/footer.json
> +  "footer_company_name_row2": "A propos",
À propos

2023-04-17 08:46 UTC, n1c01a5 commented on public/locales/fr/homepage.json
> +  "subtitle_main": "🏁La manière la plus rapide de résoudre les Issues sur Github 🐙 pour les projets Open Source 🦄",
Issues Github

2023-04-17 08:57 UTC, BLOCKCHAINDEVWEB commented on public/locales/fr/homepage.json
> +  "subtitle_main": "🏁La manière la plus rapide de résoudre les Issues sur Github 🐙 pour les projets Open Source 🦄",
ok

2023-04-17 08:57 UTC, BLOCKCHAINDEVWEB commented on public/locales/fr/footer.json
> +  "footer_company_name_row2": "A propos",
ok

2023-04-17 09:08 UTC, n1c01a5 approved these changes

2023-04-17 09:08 UTC, merged